[2024-05-29T18:57:21.966+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_location manual__2024-05-29T18:56:48.880889+00:00 [queued]>
[2024-05-29T18:57:21.974+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: conference_dag.load_location manual__2024-05-29T18:56:48.880889+00:00 [queued]>
[2024-05-29T18:57:21.975+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T18:57:21.975+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-29T18:57:21.975+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T18:57:21.987+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_location> on 2024-05-29 18:56:48.880889+00:00
[2024-05-29T18:57:21.991+0000] {standard_task_runner.py:55} INFO - Started process 40767 to run task
[2024-05-29T18:57:21.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'conference_dag', 'load_location', 'manual__2024-05-29T18:56:48.880889+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/conference_dag.py', '--cfg-path', '/tmp/tmpizxtucb5']
[2024-05-29T18:57:21.994+0000] {standard_task_runner.py:83} INFO - Job 320: Subtask load_location
[2024-05-29T18:57:22.041+0000] {task_command.py:388} INFO - Running <TaskInstance: conference_dag.load_location manual__2024-05-29T18:56:48.880889+00:00 [running]> on host 731e27f62632
[2024-05-29T18:57:22.096+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=conference_dag
AIRFLOW_CTX_TASK_ID=load_location
AIRFLOW_CTX_EXECUTION_DATE=2024-05-29T18:56:48.880889+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-29T18:56:48.880889+00:00
[2024-05-29T18:57:22.097+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-29T18:57:22.098+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'set -e; python /opt/***/mysql_utils/load_location.py']
[2024-05-29T18:57:22.106+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T18:57:22.324+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-29T18:57:22.344+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=conference_dag, task_id=load_location, execution_date=20240529T185648, start_date=20240529T185721, end_date=20240529T185722
[2024-05-29T18:57:22.366+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-05-29T18:57:22.406+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
